# Copyright 2023 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This file defines all third-party Rust dependencies approved for use
# in Chromium.
#
# Crates which do not satisfy the rule-of-2 or which are testonly must be
# marked as such in gnrt_config.toml.

[package]
name = "chromium"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
anyhow = "1"
bitflags = "1"
cfg-if = "1"
cxx = "1"
font-types = "0.4"
hex = "0.4"
hex-literal = "0.4"
lazy_static = "1"
log = "0.4"
proc-macro2 = "1"
qr_code = "2"
quote = "1"
rand = "0.8"
rand_pcg = "0.3"
read-fonts = "0.11"
regex = "1"
rstest_reuse = "0.5"
rustc-demangle-capi = "0.1"
serde = "1"
serde_json = "1"
skrifa = "0.10"
small_ctor = "0.1"
static_assertions = "1"
wycheproof = "0.4"

[dependencies.cxxbridge-cmd]
version = "1"
artifact = "bin"

[dependencies.memoffset]
version = "0.6"
features = ["unstable_const"]

[dependencies.rstest]
default-features = false
version = "0.17"

[dependencies.rustversion]
version = "1"

[dependencies.serde_json_lenient]
version = "0.1"
features = ["unbounded_depth", "float_roundtrip"]

[dependencies.syn]
version = "2"
features = ["full"]

[dependencies.unicode-linebreak]
version = "0.1"

# TODO(danakj): Remove all the patches, run cargo vendor, and commit
# all updates to dependencies that it needs to move forward.

[patch.crates-io.aho-corasick]
path = "vendor/aho-corasick-1.1.2"
package = "aho-corasick"

[patch.crates-io.anstyle]
path = "vendor/anstyle-1.0.4"
package = "anstyle"

[patch.crates-io.anyhow]
path = "vendor/anyhow-1.0.75"
package = "anyhow"

[patch.crates-io.autocfg]
path = "vendor/autocfg-1.1.0"
package = "autocfg"

[patch.crates-io.base64]
path = "vendor/base64-0.13.1"
package = "base64"

[patch.crates-io.bitflags]
path = "vendor/bitflags-1.3.2"
package = "bitflags"

[patch.crates-io.cfg-if]
path = "vendor/cfg-if-1.0.0"
package = "cfg-if"

[patch.crates-io.clap_builder]
path = "vendor/clap_builder-4.4.8"
package = "clap_builder"

[patch.crates-io.clap_lex]
path = "vendor/clap_lex-0.6.0"
package = "clap_lex"

[patch.crates-io.clap]
path = "vendor/clap-4.4.8"
package = "clap"

[patch.crates-io.codespan-reporting]
path = "vendor/codespan-reporting-0.11.1"
package = "codespan-reporting"

[patch.crates-io.cxxbridge-cmd]
path = "vendor/cxxbridge-cmd-1.0.110"
package = "cxxbridge-cmd"

[patch.crates-io.cxxbridge-macro]
path = "vendor/cxxbridge-macro-1.0.110"
package = "cxxbridge-macro"

[patch.crates-io.cxx]
path = "vendor/cxx-1.0.110"
package = "cxx"

[patch.crates-io.font-types]
path = "vendor/font-types-0.4.0"
package = "font-types"

[patch.crates-io.getrandom]
path = "vendor/getrandom-0.2.11"
package = "getrandom"

[patch.crates-io.hex-literal]
path = "vendor/hex-literal-0.4.1"
package = "hex-literal"

[patch.crates-io.hex]
path = "vendor/hex-0.4.3"
package = "hex"

[patch.crates-io.itoa]
path = "vendor/itoa-1.0.9"
package = "itoa"

[patch.crates-io.lazy_static]
path = "vendor/lazy_static-1.4.0"
package = "lazy_static"

[patch.crates-io.libc]
path = "vendor/libc-0.2.150"
package = "libc"

[patch.crates-io.link-cplusplus]
path = "vendor/link-cplusplus-1.0.9"
package = "link-cplusplus"

[patch.crates-io.log]
path = "vendor/log-0.4.20"
package = "log"

[patch.crates-io.memchr]
path = "vendor/memchr-2.6.4"
package = "memchr"

[patch.crates-io.memoffset]
path = "vendor/memoffset-0.6.5"
package = "memoffset"

[patch.crates-io.ppv-lite86]
path = "vendor/ppv-lite86-0.2.17"
package = "ppv-lite86"

[patch.crates-io.proc-macro2]
path = "vendor/proc-macro2-1.0.69"
package = "proc-macro2"

[patch.crates-io.qr_code]
path = "vendor/qr_code-2.0.0"
package = "qr_code"

[patch.crates-io.quote]
path = "vendor/quote-1.0.33"
package = "quote"

[patch.crates-io.rand_chacha]
path = "vendor/rand_chacha-0.3.1"
package = "rand_chacha"

[patch.crates-io.rand_core]
path = "vendor/rand_core-0.6.4"
package = "rand_core"

[patch.crates-io.rand_pcg]
path = "vendor/rand_pcg-0.3.1"
package = "rand_pcg"

[patch.crates-io.rand]
path = "vendor/rand-0.8.5"
package = "rand"

[patch.crates-io.read-fonts]
path = "vendor/read-fonts-0.11.2"
package = "read-fonts"

[patch.crates-io.regex-syntax]
path = "vendor/regex-syntax-0.8.2"
package = "regex-syntax"

[patch.crates-io.regex]
path = "vendor/regex-1.10.2"
package = "regex"

[patch.crates-io.rstest_macros]
path = "vendor/rstest_macros-0.17.0"
package = "rstest_macros"

[patch.crates-io.rstest_reuse]
path = "vendor/rstest_reuse-0.5.0"
package = "rstest_reuse"

[patch.crates-io.rstest]
path = "vendor/rstest-0.17.0"
package = "rstest"

[patch.crates-io.rustc-demangle-capi]
path = "vendor/rustc-demangle-capi-0.1.0"
package = "rustc-demangle-capi"

[patch.crates-io.rustc-demangle]
path = "vendor/rustc-demangle-0.1.23"
package = "rustc-demangle"

[patch.crates-io.rustc_version]
path = "vendor/rustc_version-0.4.0"
package = "rustc_version"

[patch.crates-io.rustversion]
path = "vendor/rustversion-1.0.14"
package = "rustversion"

[patch.crates-io.ryu]
path = "vendor/ryu-1.0.15"
package = "ryu"

[patch.crates-io.semver]
path = "vendor/semver-1.0.20"
package = "semver"

[patch.crates-io.serde_derive]
path = "vendor/serde_derive-1.0.192"
package = "serde_derive"

[patch.crates-io.serde_json_lenient]
path = "vendor/serde_json_lenient-0.1.8"
package = "serde_json_lenient"

[patch.crates-io.serde_json]
path = "vendor/serde_json-1.0.108"
package = "serde_json"

[patch.crates-io.serde]
path = "vendor/serde-1.0.192"
package = "serde"

[patch.crates-io.skrifa]
path = "vendor/skrifa-0.10.1"
package = "skrifa"

[patch.crates-io.small_ctor]
path = "vendor/small_ctor-0.1.1"
package = "small_ctor"

[patch.crates-io.static_assertions]
path = "vendor/static_assertions-1.1.0"
package = "static_assertions"

[patch.crates-io.strsim]
path = "vendor/strsim-0.10.0"
package = "strsim"

[patch.crates-io.syn]
path = "vendor/syn-1.0.109"
package = "syn"

[patch.crates-io.syn2]
path = "vendor/syn-2.0.39"
package = "syn"

[patch.crates-io.termcolor]
path = "vendor/termcolor-1.4.0"
package = "termcolor"

[patch.crates-io.unicode-ident]
path = "vendor/unicode-ident-1.0.12"
package = "unicode-ident"

[patch.crates-io.unicode-linebreak]
path = "vendor/unicode-linebreak-0.1.5"
package = "unicode-linebreak"

[patch.crates-io.unicode-width]
path = "vendor/unicode-width-0.1.11"
package = "unicode-width"

[patch.crates-io.winapi-util]
path = "vendor/winapi-util-0.1.6"
package = "winapi-util"

[patch.crates-io.winapi]
path = "vendor/winapi-0.3.9"
package = "winapi"

[patch.crates-io.wycheproof]
path = "vendor/wycheproof-0.4.0"
package = "wycheproof"
