
# cargo-vet audits file

[criteria.rule-of-two-safe-to-deploy]
description-url = "https://chromium.googlesource.com/chromiumos/third_party/rust_crates/+/refs/heads/main/cargo-vet/audits.toml#23"
implies = ["safe-to-deploy", "ub-risk-1"]

[criteria.crypto-safe]
description = "https://github.com/google/rust-crate-audits/blob/main/auditing_standards.md#crypto-safe"

[criteria.does-not-implement-crypto]
description-url = "https://github.com/google/rust-crate-audits/blob/main/auditing_standards.md#does-not-implement-crypto"
implies = "crypto-safe"

[criteria.ub-risk-0]
description-url = "https://github.com/google/rust-crate-audits/blob/main/auditing_standards.md#ub-risk-0"
implies = "ub-risk-1"

[criteria.ub-risk-1]
description-url = "https://github.com/google/rust-crate-audits/blob/main/auditing_standards.md#ub-risk-1"
implies = "ub-risk-2"

[criteria.ub-risk-1-thorough]
description-url = "https://github.com/google/rust-crate-audits/blob/main/auditing_standards.md#ub-risk-1-thorough"
implies = "ub-risk-1"

[criteria.ub-risk-2]
description-url = "https://github.com/google/rust-crate-audits/blob/main/auditing_standards.md#ub-risk-2"
implies = "ub-risk-3"

[criteria.ub-risk-2-thorough]
description-url = "https://github.com/google/rust-crate-audits/blob/main/auditing_standards.md#ub-risk-2-thorough"
implies = "ub-risk-2"

[criteria.ub-risk-3]
description-url = "https://github.com/google/rust-crate-audits/blob/main/auditing_standards.md#ub-risk-3"
implies = "ub-risk-4"

[criteria.ub-risk-4]
description-url = "https://github.com/google/rust-crate-audits/blob/main/auditing_standards.md#ub-risk-4"

[[audits.bytes]]
who = "agl@chromium.org"
criteria = ["safe-to-run", "does-not-implement-crypto"]
delta = "1.4.0 -> 1.5.0"

[[audits.cxx]]
who = "danakj@chromium.org"
criteria = "safe-to-run"
version = "1.0.110"

[[audits.cxxbridge]]
who = "danakj@chromium.org"
criteria = "safe-to-run"
version = "1.0.110"

[[audits.cxxbridge-flags]]
who = "danakj@chromium.org"
criteria = "safe-to-run"
version = "1.0.110"

[[audits.either]]
who = "agl@chromium.org"
criteria = ["safe-to-run", "does-not-implement-crypto"]
version = "1.9.0"

[[audits.itertools]]
who = "agl@chromium.org"
criteria = ["safe-to-run", "does-not-implement-crypto"]
version = "0.11.0"
notes = """
This is 12K lines of code, plus 6K lines of tests and benchmarks.
It has minimal use of unsafe and so I have paged though it all with \"::\"
highlighted and paid attention to which imported functions are being called.
"""

[[audits.minimal-lexical]]
who = "danakj@chromium.org"
criteria = "ub-risk-3"
version = "0.2.1"
notes = """
Reviewed in https://chromium-review.googlesource.com/c/chromium/src/+/4977110
- Unsound unsafe blocks present.
- Safe traits that can cause soundness bugs.
"""

[[audits.nom]]
who = "danakj@chromium.org"
criteria = [
    "safe-to-run",
    "rule-of-two-safe-to-deploy",
    "does-not-implement-crypto",
    "ub-risk-1",
]
version = "7.1.3"
notes = """
Reviewed in https://chromium-review.googlesource.com/c/chromium/src/+/5046153
"""

[[audits.prost]]
who = "agl@chromium.org"
criteria = ["safe-to-run", "does-not-implement-crypto"]
version = "0.12.3"

[[audits.prost-derive]]
who = "agl@chromium.org"
criteria = ["safe-to-run", "does-not-implement-crypto", "ub-risk-0"]
version = "0.12.3"
